### ISSUE TITLE
package.json missing dependencies?

### ISSUE THREAD

**Issue by katopz** [jekyll-store/front#2]
`browserify` and `uglifyjs` seem to be missing?

PS : How can I make PR in the part that's not related to `feature`? e.g. package, readme? 
From my understand as `git flow` precess I should commit to `develop` branch but I can't see any.

Thanks

**Comment by mushishi78** [comment]
You're right! Thanks for the catch.

It is fairly common to have a development branch but not necessary. It's,more useful for libraries or somethings that's been developed on by a lot of people. Whereas this project hasn't even got semVar releases because you're expected to deviate from it and not keep updated.

As for a PR that's not related to `feature`, I'm not sure what you exactly mean by that. All you need to do is fork the project, checkout a branch on your fork and then PR from that branch to my master branch. I hope that's clear :)

**Comment by katopz** [comment]
Cool, Thanks @mushishi78
